### ISSUE TITLE
网站端的右侧手机模型预览效果显示空白

### ISSUE THREAD

**Issue by imzhi** [umicro/uView1.0-doc#7]
https://v1.uviewui.com/components/button.html
如下图所示，请修复。
![image](https://user-images.githubusercontent.com/2304019/196372401-37a6cdc4-2e1f-49d5-9cd1-47b8d849e32a.png)

**Comment by imzhi** [comment]
拉了1.0文档的仓库，先搭在服务器上了。有需要的可以访问。

:heavy_check_mark: [点击访问](http://42.193.185.218:8069/)

**Comment by BeiQiaoT** [comment]
页面强制刷新即可
